### PR TITLE
At dpkg postinst, ask for reboot instead of killing desktop

### LINKED ISSUE #25: .deb post install `systemctl restart systemd-logind.service` "crashes the system"
The `systemctl restart systemd-logind.service` in [`configs/linux/postinst.sh`](https://github.com/buildbarn/bb-clientd/blob/9a547e2702e131382162583ac42c67ec8ad85436/configs/linux/postinst.sh) closes Gnome and basically crashes my Ubuntu system, it takes a few minutes before I get my screen back and a login screen. This is not really ergonomic, I didn't expect all my ongoing work to disappear.

Is there a better way to do this? Shall we change it to asking the user to reboot the computer?

### PR DESCRIPTION
**Pull request by moroten**
Instead of killing the user sessions and any desktop environments, notify the user about that a reboot is required to apply changes to `/etc/logind.conf`.

Also add version number to bb-clientd.deb and skip asking for reboot if just upgrading.

Fixes #25

### CODE REVIEW

File: configs/linux/postinst.sh [hunk 1]
```diff
@@ -7,7 +7,27 @@ if ! grep -q '^user_allow_other$' /etc/fuse.conf; then
...
 
 # Pick up changes to /etc/logind.conf.
-systemctl restart systemd-logind.service
+if [ -z "$(loginctl --no-legend list-sessions)" ]; then
+  systemctl restart systemd-logind.service
+else
+  # Restarting systemd-logind.service effectively kills user sessions and the
+  # users' desktop environment, so let the user get a hint about reboot
+  # instead.
+  if [ "$#" -ge 2 ] && [ "$1" = "configure" ]; then
```
Comment (EdSchouten) [inline configs/linux/postinst.sh:16]: Nit: can we be a bit consistent here with how we call `[` and/or `test`?

On this line we can use `[`'s own `-a` operator:

```sh
if [ "$#" -ge 2 -a "$1" = "configure" ]; then
```

And a couple of lines below we're using `test` instead of `[`:

```
if [ -e /var/run/reboot-required ]; then
```

File: BUILD.bazel [hunk 2]
```diff
@@ -35,15 +36,29 @@ pkg_tar(
     },
 )
 
+# When built with --stamp, creates a non-deterministic output file for pushing images to a remote registry.
+# With --nostamp, produces a deterministic output so dependents get cache hits.
+expand_template(
+    name = "deb_version_file",
+    out = "_deb_version.txt",
+    stamp_substitutions = {"_TAG_": "0.0.0~{{BUILD_SCM_TIMESTAMP}}-{{BUILD_SCM_REVISION}}"},
```
Comment (EdSchouten) [inline BUILD.bazel:44]: What are your thoughts on dropping the 0.0.0 prefix while we're at it? A BUILD_SCM_TIMESTAMP also happens to be a valid Debian version number, as it ends up doing a simple lexicographic comparison.

File: configs/linux/postinst.sh (hunk 1 above)
Comment (moroten) [reply configs/linux/postinst.sh:16]: I went for calling `[`. I see that you use `[` in some scripts and `test` in others.

File: configs/linux/postinst.sh [hunk 3]
```diff
@@ -7,7 +7,27 @@ if ! grep -q '^user_allow_other$' /etc/fuse.conf; then
...
+    old_version=$2
+  else
+    old_version=""
+  fi
+  # In the future, the old version can determain if reboot is required:
```
Comment (stagnation) [inline configs/linux/postinst.sh:21]: typo s/determain/determine/

File: BUILD.bazel (hunk 2 above)
Comment (moroten) [reply BUILD.bazel]: Of course, even better.

File: configs/linux/postinst.sh (hunk 3 above)
Comment (moroten) [reply configs/linux/postinst.sh]: Thank you!

Comment (stagnation) [reply configs/linux/postinst.sh]: NW, thanks for improving this :)
